version: 2
root-markers:
  - .git/
lint-debounce: 1s

tools:
  sh-shellcheck: &sh-shellcheck
    lint-command: 'shellcheck -f gcc -x'
    lint-source: 'shellcheck'
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %tote: %m'

  cpp-clang-tidy: &cpp-clang-tidy
    lint-command: 'clang-tidy'
    lint-source: 'clang-tidy'
    lint-ignore-exit-code: true
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %tote: %m'

  js-formatter: &js-formatter
    format-command: './node_modules/.bin/prettier'

  js-eslint: &js-eslint
    lint-command: './node_modules/.bin/eslint -f visualstudio --stdin --stdin-filename ${INPUT}'
    lint-source: 'eslint'
    lint-ignore-exit-code: true
    lint-stdin: true
    lint-formats:
      - "%f(%l,%c): %tarning %m"
      - "%f(%l,%c): %rror %m"

languages:
  sh:
    - <<: *sh-shellcheck

  c:
    - <<: *cpp-clang-tidy

  cpp:
    - <<: *cpp-clang-tidy

  js:
    - <<: *js-formatter
    - <<: *js-eslint

  javascript:
    - <<: *js-formatter
    - <<: *js-eslint

  javascriptreact:
    - <<: *js-formatter
    - <<: *js-eslint

  typescript:
    - <<: *js-formatter
    - <<: *js-eslint

  typescriptreact:
    - <<: *js-formatter
    - <<: *js-eslint

  vue:
    - <<: *js-formatter
    - <<: *js-eslint
