version: 2
root-markers:
  - .git/
lint-debounce: 1s

tools:
  sh-shellcheck: &sh-shellcheck
    lint-command: 'shellcheck -f gcc -x'
    lint-source: 'shellcheck'
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %tote: %m'

  dockerfile-hadolint: &dockerfile-hadolint
    lint-command: 'hadolint --no-color'
    lint-formats:
      - '%f:%l %.%.%n %tnfo: %m'
      - '%f:%l %.%.%n %tarning: %m'
      - '%f:%l %.%.%n %trror: %m'


  cpp-clang-tidy: &cpp-clang-tidy
    lint-command: 'clang-tidy'
    lint-source: 'clang-tidy'
    lint-ignore-exit-code: true
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %tote: %m'

  clang-format: &clang-format
    format-command: 'clang-format --assume-filename ${INPUT}'
    format-stdin: true
    root-markers:
      - .clang-format

  js-formatter: &js-formatter
    format-command: './node_modules/.bin/prettier --stdin-filepath ${INPUT}'
    format-stdin: true
    root-markers:
      - package.json
      - .prettierrc.js
      - .prettierrc.yml
      - .prettierrc.yaml
      - .prettierrc.toml
      - .prettierrc.json

  js-eslint: &js-eslint
    lint-command: './node_modules/.bin/eslint -f visualstudio --stdin --stdin-filename ${INPUT}'
    lint-source: 'eslint'
    lint-ignore-exit-code: true
    lint-stdin: true
    lint-formats:
      - "%f(%l,%c): %tarning %m"
      - "%f(%l,%c): %rror %m"
    root-markers:
      - package.json
      - .eslintrc.js
      - .eslintrc.yaml
      - .eslintrc.yml
      - .eslintrc.json

languages:
  sh:
    - <<: *sh-shellcheck

  c:
    - <<: *cpp-clang-tidy

  cpp:
    - <<: *cpp-clang-tidy

  js:
    - <<: *js-formatter
    - <<: *js-eslint

  javascript:
    - <<: *js-formatter
    - <<: *js-eslint

  javascriptreact:
    - <<: *js-formatter
    - <<: *js-eslint

  typescript:
    - <<: *js-formatter
    - <<: *js-eslint

  typescriptreact:
    - <<: *js-formatter
    - <<: *js-eslint

  vue:
    - <<: *js-formatter
    - <<: *js-eslint

  proto:
    - <<: *clang-format

  dockerfile:
    - <<: *dockerfile-hadolint
