version: 2
root-markers:
  - .git/
lint-debounce: 1s

tools:
  sh-shellcheck: &sh-shellcheck
    lint-command: 'shellcheck -f gcc -x'
    lint-source: 'shellcheck'
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %tote: %m'

  cpp-clang-tidy: &cpp-clang-tidy
    lint-command: 'clang-tidy'
    lint-source: 'clang-tidy'
    lint-ignore-exit-code: true
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %tote: %m'

languages:
  sh:
    - <<: *sh-shellcheck

  c:
    - <<: *cpp-clang-tidy

  cpp:
    - <<: *cpp-clang-tidy
