[[plugins]]
repo   = 'lilydjwg/colorizer'
on_cmd = ['ColorToggle', 'ColorHighlight', 'ColorClear']

[[plugins]]
repo  = 'mattn/zencoding-vim'
on_ft = ['css', 'haml', 'html', 'sass', 'scss', 'slim']

# Ruby
[[plugins]]
repo  = 'vim-ruby/vim-ruby'
on_ft = ['ruby', 'eruby']

[[plugins]]
repo  = 'slim-template/vim-slim'
on_ft = ['slim']

# Rails
[[plugins]]
repo  = 'tpope/vim-rails'
on_ft = ['ruby', 'eruby']

[[plugins]]
repo    = 'ujihisa/unite-rake'
depends = 'Shougo/unite.vim'

[[plugins]]
repo    = 'basyura/unite-rails'
depends = 'Shougo/unite.vim'

# Java
[[plugins]]
repo   = 'artur-shaik/vim-javacomplete2'
rev    = 'v2.3.5'
on_cmd = ['JCserverStart']
hook_post_source = '''
  autocmd FileType java setlocal omnifunc=javacomplete#Complete
'''

# Javascript
[[plugins]]
repo  = 'othree/yajs.vim'
on_ft = ['javascript']

[[plugins]]
repo  = 'pangloss/vim-javascript'
on_ft = ['javascript']

[[plugins]]
repo  = 'moll/vim-node'
on_ft = ['javascript']

# c#
[[plugins]]
repo = 'OmniSharp/omnisharp-vim'
on_ft = ['cs', 'csi', 'csx']
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'omnisharp-roslyn\build.ps1'
  else
    let cmd = 'sh -c "cd omnisharp-roslyn" && ./build.sh'
  endif
  let g:dein#plugin.build = cmd
'''
