[[plugins]]
repo   = 'lilydjwg/colorizer'
on_cmd = ['ColorToggle', 'ColorHighlight', 'ColorClear']

[[plugins]]
repo  = 'mattn/zencoding-vim'
on_ft = ['css', 'haml', 'html', 'sass', 'scss', 'slim']

# Ruby
[[plugins]]
repo  = 'vim-ruby/vim-ruby'
on_ft = ['ruby', 'eruby']

[[plugins]]
repo  = 'slim-template/vim-slim'
on_ft = ['slim']

# Rails
[[plugins]]
repo  = 'tpope/vim-rails'
on_ft = ['ruby', 'eruby']

[[plugins]]
repo    = 'ujihisa/unite-rake'
depends = 'Shougo/unite.vim'

[[plugins]]
repo    = 'basyura/unite-rails'
depends = 'Shougo/unite.vim'

# Java
[[plugins]]
repo   = 'artur-shaik/vim-javacomplete2'
rev    = 'v2.3.5'
on_cmd = ['JCserverStart']
hook_post_source = '''
  autocmd FileType java setlocal omnifunc=javacomplete#Complete
'''

# Javascript
[[plugins]]
repo  = 'jiangmiao/simple-javascript-indenter'
on_ft = ['javascript']
