[[plugins]]
repo   = 'lilydjwg/colorizer'
on_cmd = ['ColorToggle', 'ColorHighlight', 'ColorClear']

# Ruby
[[plugins]]
repo  = 'vim-ruby/vim-ruby'
on_ft = ['ruby', 'eruby']

[[plugins]]
repo  = 'slim-template/vim-slim'
on_ft = ['slim']

# Rails
[[plugins]]
repo  = 'tpope/vim-rails'
on_ft = ['ruby', 'eruby']

[[plugins]]
repo    = 'ujihisa/unite-rake'
depends = 'Shougo/unite.vim'

[[plugins]]
repo    = 'basyura/unite-rails'
depends = 'Shougo/unite.vim'

# Java
[[plugins]]
repo   = 'artur-shaik/vim-javacomplete2'
rev    = 'v2.3.5'
on_cmd = ['JCserverStart']
hook_post_source = '''
  autocmd FileType java setlocal omnifunc=javacomplete#Complete
'''

# Javascript
[[plugins]]
repo  = 'pangloss/vim-javascript'
on_ft = ['javascript']

[[plugins]]
repo  = 'othree/yajs.vim'
on_ft = ['javascript']

[[plugins]]
repo  = 'othree/es.next.syntax.vim'
on_ft = ['javascript']

[[plugins]]
repo  = 'MaxMEllon/vim-jsx-pretty'
on_ft = ['javascript']

[[plugins]]
repo  = 'moll/vim-node'
on_ft = ['javascript']

[[plugins]]
repo  = 'posva/vim-vue'
on_ft = ['vue']

# Typescript
[[plugins]]
repo  = 'leafgarland/typescript-vim'
on_ft = ['typescript', 'vue']

# c#
#[[plugins]]
#repo = 'OmniSharp/omnisharp-vim'
#on_ft = ['cs', 'csi', 'csx']

# go
[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']
hook_add='''
let g:go_def_mapping_enabled = 0
let g:go_doc_keywordprg_enabled = 0
'''
