[[plugins]]
repo = 'vim-jp/vimdoc-ja'
type__depth = 1

[[plugins]]
repo = 'kana/vim-fakeclip'
rev  = '0.3.0'

[[plugins]]
repo = 'vim-scripts/DirDiff.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
rev  = '4.1'

# for deoplate
[[plugins]]
repo = 'roxma/nvim-yarp'

# for deoplate
[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]]
repo = 'Shougo/neosnippet'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/vimfiler'

[[plugins]]
repo    = 'Shougo/unite-outline'
depends = 'Shougo/unite.vim'

[[plugins]]
repo    = 'Shougo/neomru.vim'
depends = 'Shougo/unite.vim'

[[plugins]]
repo = 'thinca/vim-ref'

[[plugins]]
repo  = 'w0rp/ale'
rev  = 'v2.3.0'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo    = 'maximbaz/lightline-ale'
depends = ['w0rp/ale', 'itchyny/lightline.vim']

[[plugins]]
repo = 'majutsushi/tagbar'
rev  = 'v2.6.1'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'vim-scripts/vcscommand.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'leafgarland/typescript-vim'

#[[plugins]]
#repo = 'othree/eregex.vim'

[[plugins]]
repo = 'vim-scripts/renamer.vim'

[[plugins]]
repo = 'vim-scripts/Align'

[[plugins]]
repo = 'plasticboy/vim-markdown'

[[plugins]]
repo = 'kannokanno/previm'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'ntpeters/vim-better-whitespace'

[[plugins]]
repo = 'Shougo/vimproc.vim'
rev  = 'ver.9.3'
hook_post_update = '''
  let cmd = ''
  if executable('make')
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''

[[plugins]]
repo = 'nixprime/cpsm'
hook_post_update = '''
  let cmd = ''
  if executable('make')
    let cmd = 'sh -c "PY3=ON ./install.sh"'
  endif
  let g:dein#plugin.build = cmd
'''

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

# Android
[[plugins]]
repo  = 'thinca/vim-logcat'

# Colorscheme
[[plugins]]
repo = 'jonathanfilip/vim-lucius'

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev  = 'next'
hook_post_update = '''
  let cmd = ''
  if executable('sh')
    let cmd = 'sh ./install.sh'
  endif
  let g:dein#plugin.build = cmd
'''
